### ISSUE TITLE
no PDF found error with Mendeley generated bibtex file

### ISSUE THREAD

**Issue by cryoguy** [tmalsburg/helm-bibtex#131] opened 2016-09-10 00:57 UTC
I am using pdf-tools to render pdf files. It is working fine with helm-tbibtex and org-ref.   I do not know when it stopped working.  When I am trying to open the bibtex citation link, I got "no PDFs found".  I am using Arch Linux with the most recent build. any thoughts and advise?

 I am using bibtex file generated by Mendeley with following format (note the file field):

@article{Fujishima1972,
abstract = {, Nature 238 (1972) 37–38.},
archivePrefix = {arXiv},
arxivId = {arXiv:1011.1669v3},
author = {FUJISHIMA, AKIRA and HONDA, KENICHI},
doi = {10.1038/238037a0},
eprint = {arXiv:1011.1669v3},
file = {:mnt/2nd`{\_}`BAY/papers/FUJISHIMA, HONDA - 1972 - Electrochemical Photolysis of Water at a Semiconductor Electrode - Nature.pdf:pdf},
isbn = {0028-0836},
issn = {0028-0836},
journal = {Nature},
keywords = {TiO2},
mendeley-tags = {TiO2},
month = {jul},
number = {5358},
pages = {37--38},
pmid = {12635268},
title = {{Electrochemical Photolysis of Water at a Semiconductor Electrode}},
url = {http://www.nature.com/doifinder/10.1038/238037a0},
volume = {238},
year = {1972}
}

**Comment by tmalsburg** [comment] 2016-09-11 08:07
Hi.  Thanks for reporting.  What is the actual path of the PDF file?

**Comment by cryoguy** [comment] 2016-09-13 18:57
the path is define in file tag:  /mnt/2nd{\_}BAY/papers/.  worked fine before.  Thanks.

**Comment by tmalsburg** [comment] 2016-09-17 09:09
Not sure I understand this.  Are you saying that the actual path on the disc contains the curly braces?  The issue with that would be that curly braces have special meaning in latex and they are probably removed from the path.

**Comment by tmalsburg** [comment] 2016-10-26 15:21
I'm closing this.  Feel free to reopen.

**Closed by tmalsburg** 2016-10-26 15:21 UTC

**Comment by cryoguy** [comment] 2017-04-18 18:03
Sorry to came back this issue.  I did not want open a new one.  After a h pull, helm-bibtex fail to open or attach pdf for email.  RET will take me to the entry in bibtex, and f3 go to the right article in browser.   I can still do it open PDF with the following setting using org-ref:

`(setq org-ref-get-pdf-filename-function 'org-ref-get-mendeley-filename)
;;(setq bibtex-completion-pdf-field 'org-ref-get-mendeley-filename)
(setq bibtex-completion-find-pdf-in-field 'org-ref-get-mendeley-filename)
;;(setq bibtex-completion-find-pdf 'org-ref-get-mendeley-filename)

(defun my-org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
	 (pdf-file (org-ref-get-mendeley-filename key)))
	(if (file-exists-p pdf-file)
	    (org-open-file pdf-file)
	    (message "No PDF found for %s" key))))`
I am not proficent in elisp enough to have a quick fix.  please help!!

**Comment by tmalsburg** [comment] 2017-04-18 20:40
I can't reproduce this.  I suspect that this issue is cause either by your setup or by something in org-ref.  Note that org-ref is a different package maintained by someone else.  I'd post an issue there.
