### ISSUE TITLE
Why is bibtex-completion-candidates run?

### ISSUE THREAD

**Issue by philipphoman** [tmalsburg/helm-bibtex#417] opened 2022-11-13 19:42 UTC
I'm wondering why bibtex-completion-candidates would parse my bibtex file whenever I startup emacs and run arbitrary commands e.g. org-agenda-list. It also happens when I open a org buffer that cites references in the bibtex file. Using Emacs 27.1 on MacOS 12.5 and the latest version of bibtex-completion. Thanks!

**Comment by tmalsburg** [comment] 2022-11-14 09:20
1. `bibtex-completion-candidates` should not be run on startup, but on first use of `helm-bibtex` or `ivy-bibtex`.
2. This package also doesn't run arbitrary commands.  For instance, `org-agenda-list isn't mentioned anywhere in the code as you can easily confirm.

I think the problems that you're experiencing are cause by another package, perhaps org-ref or org-roam-bibtex.  If you think they are caused by this package, please provide a minimal reproducible example (MRE) for that runs with  `emacs -Q` and I can then investigate it.  For the time being I will close this issue.  Feel free to reopen when you have a MRE.

**Closed by tmalsburg** 2022-11-14 09:20 UTC
