### ISSUE TITLE
setq bibtex-completion-additional-search-fields '(tags)) not working

### ISSUE THREAD

**Issue by yilihong** [tmalsburg/helm-bibtex#134] opened 2016-09-11 20:15 UTC
I tried the following:

`(setq bibtex-completion-additional-search-fields '(tags)))
`
and 

  ```
(with-eval-after-load 'helm-bibtex
    (setq bibtex-completion-additional-search-fields '(tags)))
```

Neither seems to work... I am on spacemacs.

The citation I have is: 

@Article{Chan2015,
  author       = {Chan, Jason and Wang, Jing},
  title        = {Hiring Preferences in Online Labor Markets: Evidence of a
                  Female Hiring Bias},
  issn         = {1556-5068},
  year         = 2015,
  doi          = {10.2139/ssrn.2619922},
  url          = {http://dx.doi.org/10.2139/ssrn.2619922},
  journal      = {SSRN Journal},
  publisher    = {Social Science Electronic Publishing},
  tags         = {workingpaper}
}

searching for workingpaper in helm-bibtex gives nothing:

<img width="575" alt="screenshot 2016-09-11 13 15 36" src="https://cloud.githubusercontent.com/assets/11595258/18420204/d88808c4-7821-11e6-8aa3-a0141c834519.png">

**Comment by jagrg** [comment] 2016-09-11 20:35
Make sure you have saved the bibtex file. Then do `C-u M-x helm-bibtex` and try again.

**Comment by yilihong** [comment] 2016-09-11 20:42
@jagrg still doesn't work :( no idea why

**Comment by yilihong** [comment] 2016-09-11 20:56
when I change it to:
```
  (eval-after-load 'helm-bibtex
    (setq bibtex-completion-additional-search-fields '(tags)))
```

Error: Symbol's function definition is void: tags

Maybe it is related to spacemacs?

**Comment by tmalsburg** [comment] 2016-09-17 09:20
Hi, I just checked on my system and it works as expected.  I simply added the following to my init.el:

``` elisp
(setq helm-bibtex-additional-search-fields '(tags))
```
I'm not familiar with spacemacs, so I can't tell whether that may somehow cause this issue.

**Comment by tmalsburg** [comment] 2016-09-24 09:12
I'm going to close this because I can't reproduce it.

**Closed by tmalsburg** 2016-09-24 09:12 UTC
