### ISSUE TITLE
Multiple file notes never fill the template

### ISSUE THREAD

**Issue by fuyu0425** [tmalsburg/helm-bibtex#340] opened 2020-10-05 07:23 UTC
https://github.com/tmalsburg/helm-bibtex/blob/12f8809aac3a13dd11a1c664a13f789005f7a199/bibtex-completion.el#L1402-L1407

`(f-exists? path)` will be always non-nil because the previous line `find-file`

**Comment by tmalsburg** [comment] 2020-10-06 11:45
> (f-exists? path) will be always non-nil because the previous line find-file

No, I don't think do.  If the file doesn't exist find-file opens an empty buffer but does not create a file on disk.  Only in this case, I'd like to write the template to the buffer.

**Comment by tmalsburg** [comment] 2020-10-06 11:46
Could you please describe the problem that you're experiencing and how to reproduce it? Thank you!.

**Comment by fuyu0425** [comment] 2020-10-06 19:38
oh really? Sorry that I am not so familiar with elisp.
maybe it is caused by my
```elisp
  (defadvice switch-to-buffer (before save-buffer-now activate)
    (when buffer-file-name (save-buffer)))

```
now I just do some hack like
```elisp
(if (f-exists? path)
              ;; First expand BibTeX variables, then org-capture template vars:
              (find-file path)
              (find-file path)
              (insert (bibtex-completion-fill-template
                       entry
                       bibtex-completion-notes-template-multiple-files)))
```

**Comment by tmalsburg** [comment] 2020-10-07 08:57
Yes, it seems you `defadvice` is causing the problem. I'm closing this issue but feel free to reopen if you encounter problems that you think are caused by a bug in helm-bitbex.

**Closed by tmalsburg** 2020-10-07 08:57 UTC
