### ISSUE TITLE
support for @string

### ISSUE THREAD

**Issue by malb** [tmalsburg/helm-bibtex#144] opened 2016-10-07 08:29 UTC
Hi there, https://cryptobib.di.ens.fr relies heavily on bibtex's `@string`. For example, cross references make use of them, e.g.:

```
@string{eurocrypt15-1 =         "EC15-1"}

@Proceedings{EC15-1,
  title =        eurocrypt15name1,
  editor =       eurocrypt15ed,
  booktitle =    eurocrypt15name1,
  volume =       eurocrypt15vol1,
  address =      eurocrypt15addr,
  month =        eurocrypt15month,
  publisher =    eurocryptpub,
  series =       mylncs,
  year =         2015,
  key =          eurocrypt15key1,
}

@InProceedings{EC:BalFauGie15,
  author =       "Josep Balasch and
                  Sebastian Faust and
                  Benedikt Gierlichs",
  title =        "Inner Product Masking Revisited",
  pages =        "486--510",
  doi =          "10.1007/978-3-662-46800-5_19",
  crossref =     eurocrypt15-1,
}
```

This means that some operations of helm-bibtex fail such as inserting a reference: `Search failed: "^@\\([^^\"@\\&$#%',={}() 	]*\\)[[:space:]]*[({][[:space:]]*eurocrypt15-1[[:space:]]*,"`

It would be nice if helm-bibtex could support this use-case.

**Comment by tmalsburg** [comment] 2016-10-07 08:39
I don't use string constants and don't really see the benefit of using them the way they are used in the example.  But I agree that it would be nice to have support for this.  PRs welcome.  If you would like to work on this, we should perhaps discuss the approach as this may have implications for performance.

**Comment by malb** [comment] 2016-10-07 09:00
I'm not too keen on string constants either, but cryptobib pretty much is the standard in my field. I shall see if I can muster enough elisp to give this a try.

**Comment by tmalsburg** [comment] 2016-10-07 10:22
Oh, I just realized that this PR would conflict with #142.  Better hold off until #142 is merged.

**Comment by tmalsburg** [comment] 2016-10-07 10:22
We should also check whether bibtex.el and/or parsebib.el have support for strings.  No need to reinvent the wheel.

**Comment by malb** [comment] 2016-10-07 15:21
Looks like parsebib parses strings https://github.com/joostkremers/parsebib/blob/master/parsebib.el#L212 My plan would be to do the replace while parsing, this way, all later operations have no slowdown. This could make crypto.bib loading very slow though …

**Comment by tmalsburg** [comment] 2016-10-26 17:00
I'm closing this because it's a duplicate of #133. #142 is merged btw, so there is nothing in the way of working on this issue.

**Closed by tmalsburg** 2016-10-26 17:00 UTC
