### ISSUE TITLE
Error when trying to edit notes

### ISSUE THREAD

**Issue by tpanum** [tmalsburg/helm-bibtex#247] opened 2018-06-12 12:40 UTC
I'm on the newest version on MELPA, and I get the following error `bibtex-completion-apa-get-value: Invalid function: (value (bibtex-completion-get-value "author" entry))` when I try to edit notes for an entry.

**Comment by tmalsburg** [comment] 2018-06-12 12:54
Duplicate of #246.  Bottom-line: bug in Emacs.  I've added a workaround yesterday.  Are you sure you have the very latest version from MELPA?

**Comment by tpanum** [comment] 2018-06-12 13:02
I'm on `helm-bibtex-20180611.935`, which is the same being displayed on the MELPA site... and I'm still having the issue :-( Emacs-wise I'm 25.3.1 ... should I try upgrading that instead?

**Comment by tmalsburg** [comment] 2018-06-12 13:16
Upgrading to 26 will fix the problem.  However, I imagine that a larger number of people might be affected, so I will add another workaround.

**Comment by tmalsburg** [comment] 2018-06-12 13:19
Should be fixed in 21f802aaf5b78dec18b72601dd8276c5244e39f5.  It will take some time until it shows up on MELPA.

**Comment by tmalsburg** [comment] 2018-06-15 16:36
I assume that the problem is solved now and will close this issue.

**Closed by tmalsburg** 2018-06-15 16:36 UTC
