### ISSUE TITLE
helm-bibtex-find-pdf-in-field fails if path contains ";" or ":"

### ISSUE THREAD

**Issue by a-fent** [tmalsburg/helm-bibtex#99] opened 2016-03-08 17:23 UTC
When retrieving a (PDF) path from a Zotero (or similar) "file" field in bibtex, helm-bibtex-find-pdf-in-field splits the string value first on ";" and then on ":" to retrieve different records and their parts of the record.

        (cl-loop  ; Looping over the files:
         for record in (s-split ";" value)
         for record = (s-split ":" record)

However, semi-colon is a valid character in a filename, and on Windows, paths will often contain colon ("C:/foo/bar"). These are escaped in Zotero's biblatex output, but simply splitting on ":" means that the paths are parsed wrongly and the function returns nil.

An example of Zotero biblatex with ":"

```
@article{thomas_why_1984,
	title = {Why Have Government Statistics? (And How to Cut their Cost)},
	volume = {4},
	issn = {0143-814X, 1469-7815},
	url = {http://www.journals.cambridge.org/abstract_S0143814X00002051},
	doi = {10.1017/S0143814X00002051},
	shorttitle = {Why Have Government Statistics?},
	pages = {85},
	number = {2},
	journaltitle = {Journal of Public Policy},
	author = {Thomas, Ray},
	urldate = {2014-03-11},
	date = {1984-05},
	keywords = {{READ}},
	file = {Thomas - 2008 - Why Have Government Statistics (And How to Cut th.pdf:C\:\\Users\\Alex\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\l8c4ybnv.default\\zotero\\storage\\SPHEAFIK\\Thomas - 2008 - Why Have Government Statistics (And How to Cut th.pdf:application/pdf}
}
```

**Comment by tmalsburg** [comment] 2016-03-08 17:42
Thanks for this detailed report.  This is slightly annoying because the fix will make parsing of the file field more costly and that will slow down the initial loading of the library even further for large bibliographies.  I feel we have to rethink how PDF are handled. Hm ...

**Comment by a-fent** [comment] 2016-03-08 17:59
Thanks for the quick reply and for this nice library.

I didn't submit a patch because I couldn't think of a neat quick way of 
fixing it without heavy-handedly regexp-matching through the bits. I 
find the parsing quick enough that I don't notice a delay when opening a 
bib with c1,000 entries, but I guess this could be a problem.

One suggestion: perhaps at the initial whole-bib-file parse time it 
could merely note that there *is* a file field, and attach an icon to 
show (possibly) attached stuff. Then only when something is done with 
the attachment(s) for a specific entry deal with parsing the field 
contents itself. This might also help with dealing with non-PDF 
attachments, e.g. HTML, images, which I sometimes have.

**Comment by tmalsburg** [comment] 2016-03-08 18:05
Just for context, some people are using helm-bibtex with bibs that contain tens of thousands of entries.  For them a further slowdown could make helm-bibtex unusable.

I like your suggestion to only check whether the file field is non-empty.  Perhaps, that's the way to go.

**Comment by a-fent** [comment] 2016-04-14 09:47
To follow-up: with the latest (20160412) helm-bibtex, this problem now causes helm-bibtex to fail completely and, unfortunately, without a clear indication of the reason why. The bibliography will be found, but no candidates will be offered. Using `bibtex-completion-candidates` shows that it's choking on:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-absolute-p(nil)
  f-absolute\?(nil)
  f-relative\?(nil)
  f-join(nil "C\\")
  bibtex-completion-find-pdf-in-field((("file" . "{Snapshot:C\\:\\\\Users\\\\Alex\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles <<snip>>
  bibtex-completion-candidates()
  eval((bibtex-completion-candidates) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

My temporary workaround is to set `helm-bibtex-pdf-field` to nil.

**Comment by tmalsburg** [comment] 2016-04-14 16:20
Thanks for reporting.  I will add a workaround later today.  Unfortunately it is really difficult to get this right, primarily because there is no formal specification of the format (correct me if I'm wrong).  Different bibliography managers (Mendeley, JabRef, ...) also use slightly different versions of the format.

**Comment by tmalsburg** [comment] 2016-04-14 20:45
I can't reproduce this with the BibTeX entry in your original description above.  Could you please send me the entry on which this code fails?  A part of the file field is shown in the backtrace but I need the complete thing.  Thank you.

**Comment by tmalsburg** [comment] 2016-04-14 20:47
One possible cause for this problem may be that `(f-root)` returns `nil` on windows.  Could you please execute `(f-root)` and report what you get?  I don't have access to a windows machine.  Thank you.

**Comment by a-fent** [comment] 2016-04-15 07:15
Thank you for looking into this. Here's an entry exported from Zotero that I think it is choking on:

```
@report{fenton_unadjusted_2015,
	title = {Unadjusted Means-Tested Benefits Rate ({UMBR}), 2001-2013},
	url = {http://eprints.lse.ac.uk/61169/},
	abstract = {The accompanying package contains an updated version of the Unadjusted Means- Tested Benefits Rate ({UMBR}) data set...},
	institution = {{CASE}, London School of Economics},
	type = {Dataset},
	author = {Fenton, Alex},
	urldate = {2015-03-12},
	date = {2015-03-02},
	langid = {english},
	file = {Snapshot:C\:\\Users\\Alex\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\l8c4ybnv.default\\zotero\\storage\\ZB9J5U43\\61169.html:text/html}
}
```

The difference, I think, is that here Zotero is exporting something with "Snapshot:" at the beginning.

You're probably right that there is no standard to which the various ref managers adhere, standardisation being driven by what CSL or Biblatex require, which doesn't include "file".

Helm-bibtex is for me quite useful enough without dealing with Zoteros' own file storage! So if it just fails without blocking the core functions that seems to me fine.

`(f-root)` works for me on both Linux and Windows, where it returns "C:\". Zotero is supposed to give me relative paths that are agnostic across the two computers and OS's I work on, but maybe I haven't configured this quite right yet.

cheers

**Comment by tmalsburg** [comment] 2016-04-17 21:50
I pushed a fix that deals with the colon in `C:\` on Windows.  Let me know if it works (I don't have Windows).  If you have colons and semicolons in file names that will still not work.  The problem is that the format of the file field is difficult to parse with regular expressions.

**Comment by tmalsburg** [comment] 2016-04-17 21:56
Does Zotero escape semicolons as `\;`?

**Comment by tmalsburg** [comment] 2016-04-17 23:29
Semicolons in file names should be fine now.  Feedback welcome.

**Closed** 2016-04-17 23:28 UTC

**Comment by a-fent** [comment] 2016-04-18 09:54
Thank you. I'm afraid I have just one more (real) edge case that ran afoul of your neat solution to unescaping the colon field separators. It occurs when a pipe character at the edge of one of the file: subfields, as in:

```
@article{bayatrizi_probleme_2012,
	title = {Un problème de chiffres : l’utilisation des connaissances empiriques en statistique dans la théorie sociale classique},
	volume = {44},
	issn = {0038-030X, 1492-1375},
	url = {http://www.erudit.org/revue/socsoc/2012/v44/n2/1012920ar.html?vue=resume&mode=restriction},
	doi = {10.7202/1012920ar},
	shorttitle = {Un problème de chiffres},
	pages = {45},
	number = {2},
	journaltitle = {Sociologie et sociétés},
	author = {Bayatrizi, Zohreh and Kemple, Thomas and Maertens, Jan},
	urldate = {2014-04-29},
	date = {2012},
	langid = {french},
	keywords = {{ACQUIRE}},
	file = {Un problème de chiffres \: l’utilisation des connaissances empiriques en statistique dans la théorie sociale classique | Érudit | Sociologie et sociétés v44 n2 2012, p. 45-73 |:C\:\\Users\\Alex\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\l8c4ybnv.default\\zotero\\storage\\WAVB2II3\\1012920ar.html:text/html}
}
```

The pipe character (which I guess has been automatically saved from a web page title) appears after "pp. 45-73" and means the split string starts "|C:\", which is an invalid path. Maybe a sequence of three different and even rarer characters might be safer?

**Comment by tmalsburg** [comment] 2016-04-18 15:35
What is the content of the first field?  Can it be anything?  I assumed that it's the file name.  At least one bibliography manager uses it for the file name, and file names can't include pipe symbols.

But you are right, it shouldn't be too hard to find a symbol sequence that has near zero probability of occurring otherwise.  Also ASCII has a [field separator character](https://en.wikipedia.org/wiki/Delimiter#ASCII_delimited_text).

**Comment by tmalsburg** [comment] 2016-04-18 16:51
Ok, now we're using record and field separator characters from the ASCII alphabet.  If someone uses them in their BibTeX file, they are asking for trouble and deserve it when this code fails :-)

**Comment by a-fent** [comment] 2016-04-19 00:55
Sounds great. The first field is a "label" field so can contain characters that would be incorrect in a filename. But not an ASCII field separator one hopes - I learnt something new too. Thanks for your patience.
