### ISSUE TITLE
Do not see any bibtex entries

### ISSUE THREAD

**Issue by cpaulik** [tmalsburg/helm-bibtex#25] opened 2014-12-27 13:52 UTC
Hi,

I tried helm bibtex with a test .bib file but I only get the fallback options and no search results. The bibtex file is validated and syntactically correct. 
For helm-bibtex I tried the latest version from github as well as the package from melpa. I use helm version helm-20141226.1305. 

No Error messages in the *Messages* Buffer

Thanks for any ideas on what could be wrong.

## Bibtex file
```
@article{Siebert2010,
title = "Quantifying blue and green virtual water contents in global crop production as well as potential production losses without irrigation ",
journal = "Journal of Hydrology ",
volume = 384,
number = "3–4",
pages = "198 - 217",
year = 2010,
note = "Green-Blue Water Initiative (GBI) ",
issn = "0022-1694",
doi = "http://dx.doi.org/10.1016/j.jhydrol.2009.07.031",
url = "http://www.sciencedirect.com/science/article/pii/S0022169409004235",
author = "Stefan Siebert and Petra Döll",
keywords = "Crop water requirement",
keywords = "Global crop water model",
keywords = "Virtual water content",
keywords = "Irrigation water use",
keywords = "Crop production",
keywords = "Crop yield "
}

@article{Zwart2010WATPRO,
title = "WATPRO: A remote sensing based model for mapping water productivity of wheat ",
journal = "Agricultural Water Management ",
volume = 97,
number = 10,
pages = "1628 - 1636",
year = 2010,
issn = "0378-3774",
doi = "http://dx.doi.org/10.1016/j.agwat.2010.05.017",
url = "http://www.sciencedirect.com/science/article/pii/S037837741000185X",
author = "Sander J. Zwart and Wim G.M. Bastiaanssen and Charlotte de Fraiture and David J. Molden",
keywords = "Water productivity",
keywords = "Global modelling",
keywords = "Benchmarking",
keywords = "Wheat",
keywords = "Remote sensing "
}
```

**Comment by joostkremers** [comment] 2015-01-01 21:13
Hi, sorry for the late reply. Holidays 'n' all...

Although I added the autoload cookies, I'm actually pretty sure they're not really needed. After all, libraries such as dash don't have any autoload cookies and they work fine.

As to what is causing the issues then, I'm really not sure. First thing I'd try is to restart Emacs. Sometimes old compiled code (not necessarily `.elc` files, also code in e.g., macros) can cause strange, inexplicable things to happen. Also try (re)installing parsebib from a fresh Emacs instance. (The problem may be related to an incorrectly installed `parsebib.el`.)

**Comment by tmalsburg** [comment] 2015-01-06 12:30
I also think that the cookies are not needed.  I read the documentation about autoloading but didn't find anything enlightening.  You added autoload cookies for some of the functions and I though that this might perhaps be interpreted to implicitely mean that the other functions should not be automatically autoloaded. That's pure speculation, though.

I agree that this issue is easy to fix but ideally users shouldn't experience this problem in the first place.  I think the strong expectation is that you install stuff through MELPA and that it just works without any manual intervention or restarting of Emacs.

**Comment by joostkremers** [comment] 2015-01-06 14:21
I agree that users should not be seeing this problem, but since I’m not able to reproduce it, I cannot debug it. I installed `parsebib` myself through Melpa as a dependency of Ebib and had no issues. I also haven’t had any reports about problems (yet!) from people upgrading Ebib to the version using `parsebib` (knock on wood…)

This, combined with the fact that loading `parsebib.el` or reinstalling `parsebib` appears to solve the issue, leads me to believe that `parsebib` itself is not the cause of the problem. Rather, something seems to go wrong with the compilation. But without access to an actual Emacs session displaying the problem, it’s impossible to tell what.

If any new information turns up, or anyone can make a suggestion as to what I can do to solve the issue, I’ll gladly see what I can do.

BTW, I'm removing the autoload cookies again. If that had actually solved anything, the current issue wouldn't have existed...

**Comment by tmalsburg** [comment] 2015-01-07 17:52
Ok, I'm closing this issue for now.

**Closed** 2015-01-07 17:51 UTC
