### ISSUE TITLE
helm-bibtex-additional-search-fileds does not work properly

### ISSUE THREAD

**Issue by Enrico68** [tmalsburg/helm-bibtex#45] opened 2015-04-14 09:27 UTC
Hello, 

thanks for this useful package. I tried to the `helm-bibtex-additional-search-fields` function for searching abstracts of my entries. This is the setup

```
(require 'helm-bibtex)
(setq helm-bibtex-bibliography "~/Documents/prova.bib")
(setq helm-bibtex-library-path "~/Dropbox/PDF")
(setq helm-bibtex-additional-search-fields '(abstract))
```

And this is a sample bib file 

```
@article{Aron2007,
    file = {Aron2007},
    author = "Aron, Adam R",
    title = "The neural basis of inhibition in cognitive control.",
    DOI = "10.1177/1073858407299288",
    volume = "13",
    number = "3",
    year = "2007",
    journal = "Neuroscientist",
    pages = "214--228",
    abstract = "The concept of "inhibition" is widely used in synaptic, circuit, and systems neuroscience, where it has a clear meaning because it is clearly observable. The concept is also ubiquitous in psychology. One common use is to connote an active/willed process underlying cognitive control. Many authors claim that subjects execute cognitive control over unwanted stimuli, task sets, responses, memories, and emotions by inhibiting them, and that frontal lobe damage induces distractibility, impulsivity, and perseveration because of damage to an inhibitory mechanism. However, with the exception of the motor domain, the notion of an active inhibitory process underlying cognitive control has been heavily challenged. Alternative explanations have been provided that explain cognitive control without recourse to inhibition as concept, mechanism, or theory. This article examines the role that neuroscience can play when examining whether the psychological concept of active inhibition can be meaningfully applied in cognitive control research.",
    month = "June"
}


@Article{BertinMaghit2009,
    abstract = {L’elettrizzazione corrisponde all’insieme delle conseguenze derivanti dall’esposizione alla corrente elettrica. L’elettrocuzione è un arresto cardiaco indotto dalla corrente elettrica. La gravità immediata dei casi di elettrizzazione con corrente a bassa tensione, essenzialmente costituiti da incidenti domestici, è cardiovascolare, con il rischio di arresto cardiaco per fibrillazione ventricolare, di asfissia per tetania dei muscoli respiratori e di infarto miocardico. La corrente ad alta tensione provoca lesioni tissutali e viscerali tra i punti di entrata e di uscita, sedi di ustioni profonde. I bisogni idroelettrolitici iniziali sono maggiori di quelli che possono essere stimati sulla base delle sole ustioni visibili. Il trattamento chirurgico richiede interventi reiterati. La fulminazione nella sua forma grave richiede una gestione simile a quella dei casi di elettrizzazione da corrente ad alta tensione.},
    file = {Bertin2009.pdf},
    doi = {10.1016/S1286-9341(09)70016-X},
    url = {http://gen.lib.rus.ec/scimag/index.php?s=10.1016/S1286-9341(09)70016-X},
    number = {2},
    volume = {13},
    year = {2009},
    journal = {EMC - Urgenze},
    title = {Elettrizzazione, elettrocuzione, fulminazione},
    author = {Bertin-Maghit, M.}
}


@article{Biffl2009,
    author = "Biffl, Walter L and Kaups, Krista L and Cothren, C Clay and Brasel, Karen J and Dicker, Rochelle A and Bullard, M Kelley and Haan, James M and Jurkovich, Gregory J and Harrison, Paul and Moore, Forrest O and others",
    title = "Management of patients with anterior abdominal stab wounds: a Western Trauma Association multicenter trial",
    file = {Biffl2009.pdf},
    volume = "66",
    number = "5",
    year = "2009",
    journal = "Journal of Trauma and Acute Care Surgery",
    pages = "1294--1301",
    abstract = "The optimal managementof hemodynamically stable, asymptomaticpatients with anterior abdominal stabwounds (AASWs) remains controversial.The goal is to identify and treat injuries in asafe, cost-effective manner. Common evaluationstrategies include local wound exploration(LWE)/diagnostic peritoneal lavage(DPL), serial clinical assessments (SCAs),and computed tomography (CT) imaging.The purpose of this multicenter study was toevaluate the clinical course of patients managedby the various strategies, to determinewhether there are differences in associatednontherapeutic laparotomy (NONTHERLAP), emergency department (ED) discharge,or complication rates."
}
```

 It seems that `helm-bibtex`looks just in the default fields. It fails to show entries when I try to use words in abstract fields.

**Comment by tmalsburg** [comment] 2015-04-15 01:45
Thanks for reporting this.  I've never used the abstract field for searching because it would give me too many matches in most situations.  I will have look as soon as I find time (which unfortunately may not be very soon).

**Comment by Enrico68** [comment] 2015-04-15 07:50
Ok. That's not a big problem.

**Comment by Zreshamwala** [comment] 2020-05-06 17:16
I am so grateful for this immensely useful package!

I am having precisely the same issue as Enrico68 except that I'm using "annotation" as the field instead of "abstract." 

Tantalizingly, when I first modified my config with `(setq helm-bibtex-additional-search-fields '(annotation))` it worked correctly, but when I closed emacs and returned, it stopped working.

My setup is comparable to Enrico68's. I am using GNU Emacs 26.3.

**Comment by Zreshamwala** [comment] 2020-05-07 00:02
Please disregard the above comment. I was able to successfully resolve this issue by updating `helm`.

**Comment by tmalsburg** [comment] 2020-05-07 08:56
Finally got to test this and failed to reproduce this problem.  Searing for content in abstracts works fine on my system.  I'll close this issue but feel free to reopen if you have a reproducible minimal example.

**Closed by tmalsburg** 2020-05-07 08:56 UTC

**Comment by tmalsburg** [comment] 2020-05-07 08:57
Since bibtex-completion is using a cache, you have to force a reload of the bibliography after changing the value of `bibtex-completion-additional-search-fields`.
