### ISSUE TITLE
show bibkey in main view

### ISSUE THREAD

**Issue by zeltak** [tmalsburg/helm-bibtex#30] opened 2015-02-01 10:41 UTC
Hi and thx for this great little helm addon.
is there anyway to have the main table show the bibkey alongside date and name?

thx!

Z

**Comment by tmalsburg** [comment] 2015-02-02 02:11
Currently there is no way to display the key that doesn't involve modifying the code.  If you want to try it, you have to make changes in the function `helm-bibtex-candidates-formatter`. You first have to extend the list of fields by the entry `=key=` and then add the key in the call to `s-format` at the end of the function.  To make space for the key, you have to shorten one or several of the other fields. Shouldn't be difficult. See the last argument for `zip-with`.

Configurable colums are planned for the future but not very high on my list of priorities because my keys are generated from the author names plus years.  When I see the authors and the year, I know what the key is.

**Comment by tmalsburg** [comment] 2015-02-02 02:15
I'll close this issue because it's a duplicate of #6.

**Closed by tmalsburg** 2015-02-02 02:15 UTC

**Comment by tmalsburg** [comment] 2016-11-10 11:18
This feature has been added #158.  There is now a lot of felxibility in how you can style the list of search results.
