### ISSUE TITLE
helm-bibtex gets stuck on "Loading blbliography ... " with newest version from MELPA

### ISSUE THREAD

**Issue by RKBK** [tmalsburg/helm-bibtex#38] opened 2015-02-18 09:59 UTC
Hi,
with the latest MELPA version of helm-bibtex (2015-02-13), I no longer get any results when trying to search for a string (even with a single character, such as "a"). Instead, the fallback menu is shown straight away, and when searching the message buffer displays only "Loading bibliography ...". However, helm-bibtex does have the correct path to the bibliography, and displays the fallback option "Create new entry in bibliography-name.bib", where bibliography-name.bib is the correct name of my bib file.

Any ideas what might be causing this to happen?

**Comment by tmalsburg** [comment] 2015-02-18 17:51
Unfortunately, helm seems to prevent error messages from appearing.  That makes it difficult to say what might be going on without further testing.  Could you please run the following command and see if it produces an error?

    (helm-bibtex-candidates)

If that works without error, please also run the following to see how many entries were read from your bibliography:

    (length (helm-bibtex-candidates))

**Comment by RKBK** [comment] 2015-02-18 20:27
When running the first command, I get

Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  #[(it) "@\227AB\207" [--cl-var--] 2](("Timestamp" . "{2012.03.13}"))
  mapcar(#[(it) "@\227AB\207" [--cl-var--] 2] (("Timestamp" . "{2012.03.13}") ("Owner" . "{rasmus}") ("Keywords" . "{selectivity, oxygen evolution, coatings, side reactions,}") ("File" . "{Couper1990 - New developments in electrode coatings for chlor-alkali processes.pdf:Couper1990 - New developments in electrode coatings for chlor-alkali processes.pdf:PDF}") ("Crossref" . "{Modernchloralkali4}") ("Pages" . "{71-83}") ("Editor" . "{Prout, N.M. and Moorhouse, J.S.}") ("Chapter" . "{8}") ("Year" . "{1990}") ("Publisher" . "{Elsevier Applied Science}") ("Booktitle" . "{Modern Chlor-alkali Technology}") ("Author" . "{Couper, A.M. and Brooks, W.N. and Denton, D.A.}") ("Title" . "{New developments in electrode coatings for chlor-alkali processes}") ("=type=" . "InCollection") ("=key=" . "Couper1990")))
  helm-bibtex-parse-bibliography()
  helm-bibtex-candidates()
  eval((helm-bibtex-candidates) nil)
  eval-expression((helm-bibtex-candidates) nil)
  call-interactively(eval-expression nil nil)

The entry that is shown is the first one in the bibliography file.

**Comment by tmalsburg** [comment] 2015-02-18 20:35
Could you please also provide me with the first entry from you BibTeX file?  Perhaps I can use it to reproduce the problem on my system.  Thanks!

**Comment by RKBK** [comment] 2015-02-18 21:55
Here's the first entry:

@InCollection{Couper1990,
  Title                    = {New developments in electrode coatings for chlor-alkali processes},
  Author                   = {Couper, A.M. and Brooks, W.N. and Denton, D.A.},
  Booktitle                = {Modern Chlor-alkali Technology},
  Publisher                = {Elsevier Applied Science},
  Year                     = {1990},
  Chapter                  = {8},
  Editor                   = {Prout, N.M. and Moorhouse, J.S.},
  Pages                    = {71-83},

  Crossref                 = {Modernchloralkali4},
  File                     = {Couper1990 - New developments in electrode coatings for chlor-alkali processes.pdf:Couper1990 - New developments in electrode coatings for chlor-alkali processes.pdf:PDF},
  Keywords                 = {selectivity, oxygen evolution, coatings, side reactions,},
  Owner                    = {rasmus},
  Timestamp                = {2012.03.13}
}

**Comment by tmalsburg** [comment] 2015-02-20 00:39
I can't reproduce this.  Could you please make sure that you are using the latest MELPA versions of the packages helm, parsebib, dash, f, and s? Also, which version of Emacs are you using?

**Comment by RKBK** [comment] 2015-02-20 09:27
Thanks @tmalsburg. I'm currently using
helm version 20150216.11
parsebib v 20150205.1305
dash v 20141220.1452
f v 20150217.328
s v 20140910.334

on emacs 
    GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)
 of 2014-03-07 on lamiak, modified by Debian

I'll try reinstalling some of those packages and see if that changes anything.

**Comment by RKBK** [comment] 2015-02-20 09:38
I noticed that there was a newer version of helm from melpa, although I already had helm installed. I installed that. That didn't help, however.

Deleting and then reinstalling parsebib didn't have any effect either.

My .emacs contains the following related to helm (I also tried (require 'helm-bibtex), but that didn't help):

; Use Helm instead of ido
; This enables matching of strings in matches, not just full matches
(require 'helm-config)
(helm-mode 1)
; Use Helm M-x menu
(global-set-key (kbd "M-x") 'helm-M-x)
; Replace yanking with Helm interface
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
; Replace buffer menu with helm-mini
(global-set-key (kbd "C-x b") 'helm-mini)
; Use Helm find files mode
(global-set-key (kbd "C-x C-f") 'helm-find-files)

; Load helm-bibtex
(require 'helm-bibtex)

; Load helm-orgcard
(require 'helm-orgcard)

(setq helm-bibtex-bibliography "~/Documents/Elektrokemidoktorand/doctorate.bib")

**Comment by RKBK** [comment] 2015-02-20 11:48
If I remove helm-bibtex from melpa, and download the helm-bibtex.el file from commit ddd626415bcb278ca1cba3c4e5b5fa8023e7c75c the full reference list works again after (load-file "~/helm-bibtex.el"). 

This is the commit preceding the one where caching of the bibliography was introduced. *However, the commit after, where caching was introduced, also works*.

(These next lines are a log of my lazy bisection attempts, so skip to the end for the conclusion.)

Going forward in time: Commit ae800a64fca318af06854c583c471c08b4f553dc *this does not work*.

Moving back to commit e049fb6ff30cf615f7692609eb643ab53f970595 *this works*

Going forward again between these two, to commit 7fb7e028e3824ec1f5e1f1351b0f9a6b33f1d37a *this works*

Going forward again to commit fcb049442de0c2bbe71efb9affa7a99fced543a5 , some of the entries get included, but not all. Only a few seem to have the author names parsed correctly, most show an empty field and only the article titles are shown.

Going to the commit just before that, 1a23dbc3432670be869a3ed0cafb39bcf910f57e , everything seems to work fine. All author names are parsed correctly, and the list pops up almost instantaneously. 

My conclusion is that there seems like the error starts in commit fcb049442de0c2bbe71efb9affa7a99fced543a5 . The first entry in my database contains a crossreference. Could there be something wrong in the way that cross references are handled? 

It seems strange that everything works on your system though, so perhaps there is something particular about my bib file. My bibliography is large, containing 1071 entries. I have no idea if that has any relation to the problem.

**Comment by tmalsburg** [comment] 2015-02-21 19:55
The size of the bibliography is not the issue.  I tested the code with crypto.bib which is gigantic and everything seemed to work nicely.   Perhaps there is an encoding issue with your bibliography.  Could you send me a zip of your bib file?  My address is: malsburg@posteo.de

**Comment by joostkremers** [comment] 2015-02-22 21:31
Hi, sorry to burst into this thread, but an issue was reported on `parsebib` that may be related:

https://github.com/joostkremers/parsebib/issues/3

There appears to be a bug in Emacs 24.3.1 that prevents `helm-bibtex-parse-bibliography` from working properly. The function `--map` doesn’t work properly, apparently because it occurs inside `cl-loop`. Replacing `--map` with `-map` (or `mapcar`) fixes the issue.

There are a few more cases where `--map` is used inside `cl-loop` in `helm-bibtex.el`, but I can’t say whether any of the other ones also cause problems. (I don’t use `helm`, so I can’t really test.)

The bug appears to have been fixed in Emacs 24.4, by the way. But it may still be worth providing a fix, because not everybody is able or willing to upgrade to 24.4.

**Comment by tmalsburg** [comment] 2015-02-22 22:41
Thank you, Joost!  I suspected that it has something to do with  `--map` but couldn't find the problem.  I replaced `--map` with `-map` (in 50fe2cbdbaba68c836268c93feb99dd514611e88).  @RKBK could you please test the latest version?

**Comment by RKBK** [comment] 2015-02-23 09:11
Hi @joostkremers and @tmalsburg,
I am pleased to say that the fix in 50fe2cbdbaba68c836268c93feb99dd514611e88 indeed seems to work fine with my bibliography. 
Thank you very much for the help.

**Comment by joostkremers** [comment] 2015-02-23 10:36
Glad I could help!

**Comment by tmalsburg** [comment] 2015-02-23 17:55
Great! I suppose, I should play it safe and also replace the other instances of `--map` inside `cl-loop`.  I must say that mixing looping idioms like that felt slightly awkward.  In that sense, I'm not too surprised that it lead to problems.

**Closed** 2015-02-23 17:55 UTC

**Comment by SebastianRiedel** [comment] 2015-05-21 15:47
Fyi, I just ran into a similar bug and found that the --map inside the cl-loop of helm-bibtex-apa-format-authors produces an error for me. Replacing the --map with a mapcar fixed my issue. Switching to emacs 24.5 fixed it as well, so that's what I ended up doing to avoid running into problems with all the other --map-s in the code.

**Comment by tmalsburg** [comment] 2015-05-21 16:49
@SebastianRiedel, thanks for the report. I suppose I should replace all `--map` by `-map` to be on the safe side.

**Comment by tmalsburg** [comment] 2015-05-21 19:42
Should be fixed in c2987ab94bb194fca0d36535f63b3bb17e6655f0.

**Comment by DiogoFerrari** [comment] 2016-04-03 20:01
I have the same problem and the update did't solve it.

**Comment by tmalsburg** [comment] 2016-04-03 20:17
@DiogoFerrari, if you don't see any entries that's usually because the bibtex file has an error.  Could you please run the following commands and report the result?

```
(helm-bibtex-candidates)
(length (helm-bibtex-candidates))
```

**Comment by DiogoFerrari** [comment] 2016-04-03 21:55
It returns 

Loading bibliography ...
forward-sexp: Scan error: "Unbalanced parentheses", 181009, 512282

**Comment by tmalsburg** [comment] 2016-04-03 22:05
Without a stacktrace, it is difficult to say what is going on exactly, but this is support for my suspicion that your bibtex file is corrupted.  The parsebib package, which we use to read bibtex, uses `forward-sexp`.    181009 is the probably the position of the opening parenthesis that has no counterpart.  (512282 is the position where the file ends.)  You can use `(goto-char 181009)` in the bibtex file to find this unmatched parenthesis.

**Comment by DiogoFerrari** [comment] 2016-04-03 22:12
@tmalsburg, you were right. I have found the error. It was an additional { in one of the fields of a bib file entry. Everything is working fine again. Thanks.

**Comment by tmalsburg** [comment] 2016-04-03 22:20
Great.  I have added a new section about this to the documentation: https://github.com/tmalsburg/helm-bibtex#helm-bibtex-doesnt-show-any-entries
