### ISSUE TITLE
multiple citations for dummies

### ISSUE THREAD

**Issue by rytis-paskauskas** [tmalsburg/helm-bibtex#109] opened 2016-04-27 11:30 UTC
I'd like to obtain a string containing multiple citations like so
`\cite{A,B,C}`
I get the C-SPC part for selecting multiple entries. But then I'm stuck: I press f1, and then only the citation under the cursor is inserted like so
`\cite{D}`
I'd appreciate the specific instruction.

**Comment by jagrg** [comment] 2016-04-27 12:33
It doesn't work for me either.

@tmalsburg One solution is to replace `(if (listp candidates) candidates (list candidates)))` with `(helm-marked-candidates)` in the `bibtex-completion-insert-reference` function.

**Comment by tmalsburg** [comment] 2016-04-27 16:15
Thanks for reporting, @rytis-paskauskas.  This is a little strange, I have to say.  If you press tab and then select "insert citation", it works as expected.

@jagrg the code already uses `helm-marked-candidates`.  See https://github.com/tmalsburg/helm-bibtex/blob/master/helm-bibtex.el#L159  And bibtex-completion should not contain references to helm because it is also used by ivy-bibtex.

**Comment by tmalsburg** [comment] 2016-04-27 16:41
Just tested it.  I can't reproduce this problem.  Pressing `f3` inserts multiple citations just fine.  I suspect that something is off in your configuration of helm-bibtex.

**Comment by rytis-paskauskas** [comment] 2016-04-27 16:54
The only helm-bibtex-related configuration I have in custom.el is the following:
`(setq helm-bibtex-bibliography '("~/Projects/bikes/bikesharing.bib"))
(setq helm-bibtex-library-path '("~/Bibliography/PDF"))`

Am I missing something relvant?

I also require and similarly configure org-ref, but it couldn't be that could it?

**Comment by rytis-paskauskas** [comment] 2016-04-27 17:07
Famous last words! I use org-ref as well. When I switch it off, helm-bibtex works as expected.

**Comment by tmalsburg** [comment] 2016-04-27 17:31
Thanks for the update.  I'll close this issue and follow the one you created in [org-ref](https://github.com/jkitchin/org-ref/issues/199).

**Closed by tmalsburg** 2016-04-27 17:31 UTC
