### ISSUE TITLE
Open PDF for bib entry containing point (enhancement request)

### ISSUE THREAD

**Issue by higham** [tmalsburg/helm-bibtex#121] opened 2016-08-05 19:19 UTC
It would be very nice if there was a command to open the PDF for the bib entry the point  is located within (i.e., in the bib file).  At the moment the only way I can see to do this is to move the point to the key, call helm-bibtex, press M-n, then hit enter.

**Comment by tmalsburg** [comment] 2016-08-05 19:59
This sounds useful indeed.  Unfortunately, I won't have time to work on this over the next couple of weeks or even months (new job, transatlantic move, ...).  It shouldn't be too hard, though, to implement this.  bibtex.el probably has tools in place for extracting the bibtex key from the entry at point and once you have that you can pass it to `bibtex-completion-open-pdf`.  PR welcome.

**Comment by jagrg** [comment] 2016-08-05 20:39
I'm not sure if bibtex.el has anything specific to extract the key. Maybe I didn't look close enough, but here's a starting point:

```elisp
(defun bibtex-open-pdf ()
  (interactive)
  (save-excursion
    (bibtex-beginning-of-entry)
    (let* ((key (reftex-get-bib-field "=key=" (bibtex-parse-entry t)))
	   (pdf (car (bibtex-completion-find-pdf-in-library key))))
      (if pdf
	  (funcall bibtex-completion-pdf-open-function pdf)
	(message "No PDF found for %s" key)))))
```

**Comment by tmalsburg** [comment] 2016-08-05 22:33
Great, thanks @jagrg.  Here's a version that does the same but without using reftex:

``` elisp
(defun bibtex-completion-open-pdf-of-entry-at-point ()
  (interactive)
  (save-excursion
    (bibtex-beginning-of-entry)
    (when (looking-at bibtex-entry-maybe-empty-head)
      (bibtex-completion-open-pdf (bibtex-key-in-head)))))
```

@higham, does this work for you?

**Comment by higham** [comment] 2016-08-06 14:27
Yes - bibtex-completion-open-pdf-of-entry-at-point works perfectly!
Thanks to both of you.  This is something I will use multiple times per day.

**Comment by tmalsburg** [comment] 2016-08-08 16:54
Glad to hear.  Now the question is how and whether we should integrate this into helm-bibtex since this is slightly outside its scope.  For example, should we assign a default key binding?

**Comment by higham** [comment] 2016-08-08 17:55
Personally, I would say yes. I've set C-c p. I've also made a trivial
modification of the macro to call bibtex-completion-edit-notes on the
current bib entry, assigning it to C-c n. Of course, I now also want to be
able to do both actions with the point on the cite command in the LaTeX
file!  The obvious, rather crude code

(defun njh-open-cite-pdf ()
  (interactive)
  (save-excursion
  (reftex-view-crossref) (switch-window)
   (bibtex-completion-open-pdf-of-entry-at-point)(delete-window)))

seems to work.

**Comment by tmalsburg** [comment] 2016-08-08 18:08
Thanks for these suggestions.  All this is very useful but we have to be clear that we're effectively starting to build the latex equivalent of org-ref, which is not a bad thing but something else than what helm-bibtex used to be.  I'll think about how to approach this.

**Comment by jagrg** [comment] 2016-08-10 10:42
> I now also want to be able to do both actions with the point on the cite command in the LaTeX file! 

I've tried something similar with org-ref before. You can see the idea [here](https://cloud.githubusercontent.com/assets/8846979/16577084/027db862-428b-11e6-9206-44fa973aa7fe.gif). A keymap works well too. Anyhow, this is experimental, but you can see it in the code below adapted to latex. We could also add the actual bibtex-completion source below, possibly omitting the references already cited in the buffer.

The idea is to prioritise those used in the buffer and make the selection process quicker. At some point I also thought about counting the number of times a reference appears in the buffer and using that information to sort candidates accordingly. Anyway, something more to think about.

```elisp
(defun bibtex-completion-keys ()
  (interactive)
  (let ((keys nil))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "\\\\cite+?" nil t)
	(re-search-forward "{" nil t)
	(let ((key (thing-at-point 'symbol t)))
	  (cl-pushnew key keys :test #'equal))))
        (helm :sources
	      (helm-build-sync-source "Keys"
		:candidates (nreverse keys)
		:action '(("Open pdf" . (lambda (candidate)
					  (bibtex-completion-open-pdf candidate)))
			  ("Open notes" . (lambda (candidate)
					    (bibtex-completion-edit-notes candidate))))
		:keymap test-map))))

(defun test-open-pdf ()
  (interactive)
  (helm-exit-and-execute-action 'helm-bibtex-open-pdf))

(defun test-open-notes ()
  (interactive)
  (helm-exit-and-execute-action 'bibtex-completion-edit-notes))

(defvar test-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map helm-map)
    (define-key map (kbd "C-c p") 'test-open-pdf)
    (define-key map (kbd "C-c n") 'test-open-notes)
    map))
```

**Comment by tmalsburg** [comment] 2016-10-06 18:03
Perhaps interesting: https://github.com/plantarum/bibtex-utils

**Comment by plantarum** [comment] 2016-10-14 13:31
Yes, [bu-open-doc](https://github.com/plantarum/bibtex-utils/blob/master/bibtex-utils.el#L144) will open the document (pdf first, then tries URL or DOI) for the bibtex entry at point (point being anywhere in the entry). [bu-jump-to-doc](https://github.com/plantarum/bibtex-utils/blob/master/bibtex-utils.el#L181) does the same from a bibtex citation in a LaTeX document.

My workflow currently includes a mix of helm-bibtex and regular bibtex-mode + my bibtex-utils enhancements. I'm happy to roll anything from bibtex-utils into helm-bibtex that makes sense.

**Comment by tmalsburg** [comment] 2016-10-14 13:42
The question is whether it makes sense to duplicate functions from bibtex-utils in helm-bibtex.  Perhaps, it's enough to have a document that gives users an overview of what's out there and how to combine it.  I must admit, my knowledge of bibtex.el and some other relevant packages is only rudimentary.

**Comment by plantarum** [comment] 2016-10-14 14:37
I wasn't thinking of duplicating the functions, but of moving them permanently from one package to the other. But the more I think about that, the less I like the idea. Some people might prefer only the helm-bibtex approach or only the more standard bibtex-utils approach, and some of us might like to combine both (as I do).

So your suggestion makes sense, perhaps we could document the relationship between the two in the package readme files. If I have time to think this over some more, I'll put together a pull request.

**Comment by tmalsburg** [comment] 2016-10-14 14:53
Ah, I see.  One benefit of combining them would be that in helm-bibtex already has the logic for locating PDF files referenced in the `file` field.  And we could also add a function for accessing helm-bibtex-style notes from the bib-file.

**Comment by ericdanan** [comment] 2017-09-22 13:29
Perhaps a simple and flexible approach could be to make `helm-bibtex` and `ivy-bibtex` preselect the entry at point, so that we can then quickly access all the bibtex-completion actions (open pdf, open notes, and so on). Basically we would only need to write a function returning the relevant bibtex key (most often this would be merely the key at point, but it could be more sophisticated in some contexts, eg retrieving the key of the entry at point when in bibtex mode). I can try and send a PR if you are interested.

**Comment by tmalsburg** [comment] 2017-09-22 13:37
@ericdanan I think this is a great idea because this approach doesn't require any new UI components but is working with what we already have in place.  Clarification question: What do you mean by pre-select?  Would the user see only the entry at point in the helm / ivy interface?  Or would they see the complete list with just the cursor on the entry in question?  In the latter case, we'd have the problem that helm (and perhaps ivy) is not showing the complete list of entries but only entries up to a configurable maximum.

**Comment by ericdanan** [comment] 2017-09-22 13:49
I mean seeing the whole list with the entry selected, so that we can directly call the actions on this entry or alternatively start typing a search string if we are looking for another entry. Ivy doesn't have the problem you mention since all candidates are shown. If helm truncates the candidate list then I understand it could be an issue. Perhaps then one should move the entry to the top of the candidates list instead.

**Comment by tmalsburg** [comment] 2017-09-22 14:38
Moving the entry to the top of the list is not ideal but perhaps good enough for now.  An alternative would be to just display the whole list but for large bibliographies this might be too slow.  Not sure.

**Comment by ericdanan** [comment] 2017-09-22 20:23
I don't know if removing the candidate number limit would be problematic for some users.

Yet another alternative would be to add a source with only the entry at point before the main ("Bibtex entries") source. I suppose that when calling `helm-bibtex`, this entry would then be selected when there is one and the source would not be displayed at all otherwise. Perhaps one could even arrange that only the empty string matches in this source, so we move to the main source as soon as we start typing. What do you think?

**Comment by jagrg** [comment] 2017-09-22 21:08
> Yet another alternative would be to add a source with only the entry
> at point before the main ("Bibtex entries") source.

That could work. Another option would be to count the number of entries
before (or after) the entry at point and use helm-next-line to move the
cursor down without having to narrow the list.

On 22 Sep 2017, Eric Danan <notifications@github.com> wrote:

> I don't know if removing the candidate number limit would be problematic for some users.
>
> Yet another alternative would be to add a source with only the entry at point before the main ("Bibtex entries") source. I suppose that when calling `helm-bibtex`, this entry would then be selected when there is one and the source would not be displayed at all otherwise. Perhaps one could even arrange that only the empty string matches in this source, so we move to the main source as soon as we start typing. What do you think?


-- 
Jonathan
Monthly Atmospheric CO₂: August 2017: 405.07, August 2016: 402.25

**Comment by jagrg** [comment] 2017-09-22 23:12
This is what I had in mind. Do `M-x my-test` in one of your bibtex entries, and the line should move to the corresponding candidate.
```
(defun my-test ()
  (interactive)
  (let ((key (save-excursion
	       (bibtex-beginning-of-entry)
	       (when (looking-at bibtex-entry-maybe-empty-head)
		 (bibtex-key-in-head))))
	(counter)
	(bibtex-completion-bibliography (bibtex-completion-find-local-bibliography)))
    (with-temp-buffer
      (mapcar (lambda (x)
		(insert-file-contents x))
	      bibtex-completion-bibliography)
      (goto-char (point-min))
      (if key
	  ;; If we have key at point, count the number of entries
	  ;; thereafter
	  (when (re-search-forward key nil t)
	    (setq counter (count-matches "\\(^@\\)")))
	;; Otherwise set the counter to 0 to void preselect
	(setq counter 0)))
    (helm :sources (list power-ref-bibtex-source power-ref-fallback-source)
	  :preselect (lambda () (unless (= 0 counter)
				  (helm-next-line counter)))
	  :candidate-number-limit 500
	  :buffer "*helm-bibtex test*")))
```

**Comment by tmalsburg** [comment] 2017-09-26 17:39
Sorry for the slow response. @jagrg does `helm-next-line` load more entries when the entry in question is beyond the `candidate-number-limit`?  If yes, this approach would be viable.

**Comment by jagrg** [comment] 2017-09-26 18:22
I think the answer is no. The function won't work if the entry at point is beyond the candidate-number-limit. Good point BTW.

**Comment by tmalsburg** [comment] 2017-09-26 18:46
Well, then let's set the `candidate-numer-limit` temporarily to `nil` when the helm-bibtex is called on a BibTeX entry.  Would that work?  Alternatively, `helm-show-all-in-this-source-only` may do the trick.

By the way calculating the position of the entry is a bit more complex because the position in the file is not necessarily the position in the displayed list.  This is the case when there are multiple BibTeX files.  Better to calculate the position via `bibtex-completion-cache`.  In this case, the position should be calculated after helm-bibtex was started because the entries in the cache may change when helm-bibtex is initialized.

**Comment by jagrg** [comment] 2017-09-27 12:20
> By the way calculating the position of the entry is a bit more complex because the position in the file is not necessarily the position in the displayed list. This is the case when there are multiple BibTeX files.

I have two bib files set and the command above works fine for both. If we want to add this feature to helm-bibtex-with-local-bibliography (or as a separate function), then I don't think this is an issue since the function uses the local file to generate the bibliography, which is all we need to get the entry at point.

>  Better to calculate the position via bibtex-completion-cache. In this case, the position should be calculated after helm-bibtex was started because the entries in the cache may change when helm-bibtex is initialized.

I think the only way the function would fail to find the correct candidate is if we add or delete entries and try opening helm-bibtex without saving the buffer first. If that's an issue, we can still save the bib file at point pragmatically. Otherwise, how can we reproduce the wrong calculation?

**Comment by tmalsburg** [comment] 2017-09-27 14:21
> I have two bib files set and the command above works fine for both.

Ah sorry, I see, you're right.

> I think the only way the function would fail to find the correct candidate is if we add or delete entries and try opening helm-bibtex without saving the buffer first. If that's an issue, we can still save the bib file at point pragmatically. Otherwise, how can we reproduce the wrong calculation?

Not sure whether we should save the bib file.  It should be the user's decision when and what to save.  I think I'd prefer a solution using the cache.  One benefit would be that it's faster in most cases because you wouldn't have to read the bibliography from disk (can be large for people).  Also less code (I think).  Does helm have a hook for doing things once its interface is up?

**Comment by ericdanan** [comment] 2017-09-27 14:45
We can use `cl-position-if` to find the index of the candidate at point in `(bibtex-completion-candidates)` (I generated a list of 100k candidates and tried it and it took 0.05 seconds to find a candidate at the end of the list). Then we can use the helm `:preselect` slot to call `helm-next-line` with that index. It seems to work, but I'll test a bit more. Should be able to send a PR tonight.

**Comment by jagrg** [comment] 2017-09-27 14:59
@tmalsburg  I think the command already uses the cache. If I run my-test the first time it takes a bit longer to load. If I run a second time, the helm buffer opens instantly with no delays. Anyway looking forward to seeing @ericdanan 's solution.

**Comment by tmalsburg** [comment] 2017-09-29 17:48
@higham I just merged @ericdanan's PR that adds this feature.  When point is on a BibTeX entry, a BibTeX key within a citation macro, or on an org-bibtex entry, the publication is preselected in helm-bibtex and ivy-bibtex. Thanks everyone for your input.

**Closed by tmalsburg** 2017-09-29 17:48 UTC
Labels: enhancement
