### ISSUE TITLE
Error (use-package): helm-bibtex/:catch: Symbol’s value as variable is void: helm-buffers-run-browse-project

### ISSUE THREAD

**Issue by nilsleh** [tmalsburg/helm-bibtex#409] opened 2022-09-21 10:23 UTC
Hi, thank you for the awesome work. 

I am a new emacs user trying to use helm-bibtex with org-roam and org-roam-bibtex as a note taking and knowledge base for academic work. Currently, I am running into 
`Error (use-package): helm-bibtex/:catch: Symbol’s value as variable is void: helm-buffers-run-browse-project` and cannot figure out what is causing it.

I am using Ubuntu 20.4 and Emacs 28.1.

This is my init file:
```
(use-package helm-bibtex
  :config (setq bibtex-completion-bibliography '("~/path/")
                bibtex-completion-library-path
                '("~/path/")
                bibtex-completion-notes-path
                "~/path/"))
```

Trying to delete and reinstall helm-bibtex yields the following during installation:
`helm-bibtex.el:99:1: Error: Symbol’s value as variable is void: helm-buffers-run-browse-project`

**Comment by tmalsburg** [comment] 2022-09-23 13:20
I haven't encountered this error yet and helm-bibtex actually doesn't use the function `helm-buffers-run-browse-project`, at least not directly. Perhaps, this is caused by some interaction with org-roam-bibtex? Could you try running helm-bibtex without org-roam-bibtex?

**Comment by nilsleh** [comment] 2022-09-23 13:26
I uninstalled org-roam-bibtex and helm-bibtex and tried to install helm-bibtex and encountered:
```
helm-buffers.el:1163:32: Warning: reference to free variable
    ‘helm-buffers-run-browse-project’

In end of data:
helm-buffers.el:1163:2: Warning: the function ‘helm-make-command-from-action’
    is not known to be defined.
helm-buffers.el:242:41: Warning: the function
    ‘helm-buffers-run-browse-project’ is not known to be defined.
```

**Comment by tmalsburg** [comment] 2022-09-23 13:27
Could you please produce a minimal reproducible example that I can use to debug this?  Thank you.

**Comment by nilsleh** [comment] 2022-09-30 11:47
I tried several things with helm-bibtex and helm but did not manage to figure out a solution. So I switched to ivy-bibtex and that is working! I assume something else was therfore causing this issue. Apologies for the inconvenience.

**Comment by tmalsburg** [comment] 2022-10-04 10:06
No need to apologize.  I'll close this issue, but feel free to reopen if you find a way to reproduce this issue in a minimal example.

**Closed by tmalsburg** 2022-10-04 10:06 UTC
