### ISSUE TITLE
allow customization on the display window

### ISSUE THREAD

**Issue by RNAer** [tmalsburg/helm-bibtex#110] opened 2016-06-01 00:10 UTC
For example, it would be very useful to show journal, publication year, etc. in the display window. Maybe helm-bibtex can do it, but I can't find the documentation on how to do it.

**Comment by tmalsburg** [comment] 2016-06-01 00:50
This is a duplicate of #6.  There is currently no way to customize the layout, but I agree that this would be useful.  Someone needs to write a general package for table formatting.  This would be tremendously useful in many contexts, e.g., almost all helm sources, Mu4e, etc.  I have a relatively clear vision of it but no time to write it.

**Closed by tmalsburg** 2016-06-01 00:50 UTC

**Comment by RNAer** [comment] 2016-06-01 05:35
Yeah, that is very unfortunate. this is actually a deal breaker to me,
although helm-bibtex works great.

**Comment by tmalsburg** [comment] 2016-06-01 14:40
You you really want your custom layout, you can modify the function `bibtex-completion-candidates-formatter` to include your extra columns.  You also have to add those properties to `bibtex-completion-additional-search-fields` because otherwise they will not be loaded.  Shouldn't be too hard.  Let me know how it goes.

**Comment by tmalsburg** [comment] 2016-11-10 11:18
This feature has been added #158. There is now a lot of felxibility in how you can style the list of search results.
