### ISSUE TITLE
eval (featurep 'helm-bibtex) gives nil.

### ISSUE THREAD

**Issue by hongyi-zhao** [tmalsburg/helm-bibtex#432] opened 2023-05-15 03:33 UTC
In my case, the configuration for helm and helm-bibtex is as follows:

```elisp
(use-package helm
  :bind (:map helm-command-map
          ("C-c h" . helm-execute-persistent-action)))

(use-package helm-bibtex
  :init
  (setq
   bibtex-completion-pdf-field "File"
   ;;https://github.com/tmalsburg/helm-bibtex#insert-latex-cite-commands
   bibtex-completion-cite-prompt-for-optional-arguments nil)

  :bind-keymap
  ("<menu>" . helm-command-prefix)
  :bind
  (
   :map helm-command-map
   ("b" . helm-bibtex)
   ("B" . helm-bibtex-with-local-bibliography)
   ("n" . helm-bibtex-with-notes)
   ("<menu>" . helm-resume)
   )

  :config
  (require 'helm-config)
  ;;https://github.com/tmalsburg/helm-bibtex#application-used-for-opening-pdfs
  ;;https://github.com/tmalsburg/helm-bibtex/issues/386
  (defun bibtex-completion-open-pdf-external (keys &optional fallback-action)
    (let ((bibtex-completion-pdf-open-function
       (lambda (fpath) (start-process "evince" "*helm-bibtex-evince*"
"/usr/bin/evince" fpath))))
      (bibtex-completion-open-pdf keys fallback-action)))

  (helm-bibtex-helmify-action bibtex-completion-open-pdf-external
helm-bibtex-open-pdf-external)

  (helm-add-action-to-source
   'helm-bibtex
   '(("P" helm-bibtex-open-pdf-external "Open PDF file in external
viewer (if present)")))

  ;;https://github.com/tmalsburg/helm-bibtex#browser-used-for-opening-urls-and-dois
  (setq bibtex-completion-browser-function
    (lambda (url _) (start-process "firefox" "*firefox*" "firefox" url)))

  )
```
With the above setting, I still observed the following result:

`C-x b *scratch* RET`  then in scratch buffer eval `(featurep 'helm-bibtex)` by `C-x C-e` gives nil.

Then, I try to eval `(require 'helm-bibtex)` in scratch buffer and the following error will be triggered:

```elisp
Debugger entered--Lisp error: (file-missing "Cannot open load file"
"No such file or directory" "helm-config")
  require(helm-config)
  (progn (require 'helm-config) (defalias
'bibtex-completion-open-pdf-external #'(lambda (keys &optional
fallback-action) (let ((bibtex-completion-pdf-open-function #'...))
(bibtex-completion-open-pdf keys fallback-action))))
(helm-bibtex-helmify-action bibtex-completion-open-pdf-external
helm-bibtex-open-pdf-external) (helm-add-action-to-source 'helm-bibtex
'(("P" helm-bibtex-open-pdf-external "Open PDF file in external viewer
(if present)"))) (setq bibtex-completion-browser-function #'(lambda
(url _) (start-process "firefox" "*firefox*" "firefox" url))) t)
  (condition-case err (progn (require 'helm-config) (defalias
'bibtex-completion-open-pdf-external #'(lambda (keys &optional
fallback-action) (let ((bibtex-completion-pdf-open-function ...))
(bibtex-completion-open-pdf keys fallback-action))))
(helm-bibtex-helmify-action bibtex-completion-open-pdf-external
helm-bibtex-open-pdf-external) (helm-add-action-to-source 'helm-bibtex
'(("P" helm-bibtex-open-pdf-external "Open PDF file in external viewer
(if present)"))) (setq bibtex-completion-browser-function #'(lambda
(url _) (start-process "firefox" "*firefox*" "firefox" url))) t)
((debug error) (funcall use-package--warning56 :config err)))
  (lambda nil (condition-case err (progn (require 'helm-config)
(defalias 'bibtex-completion-open-pdf-external #'(lambda (keys
&optional fallback-action) (let (...) (bibtex-completion-open-pdf keys
fallback-action)))) (helm-bibtex-helmify-action
bibtex-completion-open-pdf-external helm-bibtex-open-pdf-external)
(helm-add-action-to-source 'helm-bibtex '(("P"
helm-bibtex-open-pdf-external "Open PDF file in external viewer (if
present)"))) (setq bibtex-completion-browser-function #'(lambda (url
_) (start-process "firefox" "*firefox*" "firefox" url))) t) ((debug
error) (funcall use-package--warning56 :config err))))()
  eval-after-load-helper("/home/werner/.emacs.d/straight/build/helm-bibtex/h...")
  run-hook-with-args(eval-after-load-helper
"/home/werner/.emacs.d/straight/build/helm-bibtex/h...")
  do-after-load-evaluation("/home/werner/.emacs.d/straight/build/helm-bibtex/h...")
  require(helm-bibtex)
  (progn (require 'helm-bibtex))
  eval((progn (require 'helm-bibtex)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

What do these problems mean, and do they indicate a corresponding bug in the `helm-bibtex` package?

See [here](https://github.com/tmalsburg/helm-bibtex/issues/431#issuecomment-1545772936) and [here](https://lists.gnu.org/archive/html/help-gnu-emacs/2023-05/msg00124.html) for the related discussions.

Regards,
Zhao

**Comment by tmalsburg** [comment] 2023-05-15 07:13
If I understand correctly, your Emacs fails to execute the command `(require 'helm-config)`.  If true, this suggests a faulty helm configuration.  (And other users had similar problems in the past.)  Please make sure helm is installed and configured exactly as recommended.  I'm closing this now, but Feel free to reopen this issue if you come to the conclusion that the problem is in helm-bibtex, after all.

**Closed by tmalsburg** 2023-05-15 07:13 UTC

**Comment by hongyi-zhao** [comment] 2023-05-15 07:44
According to the description [here](https://github.com/emacs-helm/helm/wiki#configure):

> Note: In the past we had a file called “helm-config.el” that was needed for installation from source only (most people were requiring it with an installation from package which was unuseful) the file doesn’t exists anymore, therefore if you try to require it you will have an error.

It seems that `(require 'helm-config)` shouldn't be used now.

**Comment by tmalsburg** [comment] 2023-05-15 09:45
Ah, I see.  The code doesn't use `(require 'helm-config)` anywhere but it was used in the documentation.  I removed it.  Thank you!

**Comment by hongyi-zhao** [comment] 2023-05-16 00:16
I've removed the `(require 'helm-config)` from my init.el, but when I eval `(require 'helm-bibtex)` in scratch buffer still gives the following error:

```elisp
Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 4) 2)
  helm-add-action-to-source(helm-bibtex (("P"
helm-bibtex-open-pdf-external "Open PDF file in external viewer (if
present)")))
  (progn (defalias 'bibtex-completion-open-pdf-external #'(lambda
(keys &optional fallback-action) (let
((bibtex-completion-pdf-open-function #'...))
(bibtex-completion-open-pdf keys fallback-action))))
(helm-bibtex-helmify-action bibtex-completion-open-pdf-external
helm-bibtex-open-pdf-external) (helm-add-action-to-source 'helm-bibtex
'(("P" helm-bibtex-open-pdf-external "Open PDF file in external viewer
(if present)"))) (setq bibtex-completion-browser-function #'(lambda
(url _) (start-process "firefox" "*firefox*" "firefox" url))) t)
  (condition-case err (progn (defalias
'bibtex-completion-open-pdf-external #'(lambda (keys &optional
fallback-action) (let ((bibtex-completion-pdf-open-function ...))
(bibtex-completion-open-pdf keys fallback-action))))
(helm-bibtex-helmify-action bibtex-completion-open-pdf-external
helm-bibtex-open-pdf-external) (helm-add-action-to-source 'helm-bibtex
'(("P" helm-bibtex-open-pdf-external "Open PDF file in external viewer
(if present)"))) (setq bibtex-completion-browser-function #'(lambda
(url _) (start-process "firefox" "*firefox*" "firefox" url))) t)
((debug error) (funcall use-package--warning56 :config err)))
  (lambda nil (condition-case err (progn (defalias
'bibtex-completion-open-pdf-external #'(lambda (keys &optional
fallback-action) (let (...) (bibtex-completion-open-pdf keys
fallback-action)))) (helm-bibtex-helmify-action
bibtex-completion-open-pdf-external helm-bibtex-open-pdf-external)
(helm-add-action-to-source 'helm-bibtex '(("P"
helm-bibtex-open-pdf-external "Open PDF file in external viewer (if
present)"))) (setq bibtex-completion-browser-function #'(lambda (url
_) (start-process "firefox" "*firefox*" "firefox" url))) t) ((debug
error) (funcall use-package--warning56 :config err))))()
  eval-after-load-helper("/home/werner/.emacs.d/straight/build/helm-bibtex/h...")
  run-hook-with-args(eval-after-load-helper
"/home/werner/.emacs.d/straight/build/helm-bibtex/h...")
  do-after-load-evaluation("/home/werner/.emacs.d/straight/build/helm-bibtex/h...")
  require(helm-bibtex)
  (progn (require 'helm-bibtex))
  eval((progn (require 'helm-bibtex)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
 
```

**Comment by hongyi-zhao** [comment] 2023-05-16 03:46
Finally, It solved the problem discussed here with the following simpler configuration:

```elisp
;; https://github.com/emacs-helm/helm/wiki#if-installed-from-source
;; First issue the following command
/home/werner/.emacs.d/straight/repos/helm$ make
(use-package helm :config (require 'helm-autoloads))

(use-package helm-bibtex
  :init
  (setq
   bibtex-completion-pdf-field "File"
   ;;https://github.com/tmalsburg/helm-bibtex#insert-latex-cite-commands
   bibtex-completion-cite-prompt-for-optional-arguments nil)

  :bind-keymap
  ("<menu>" . helm-command-prefix)
  :bind
  (
   :map helm-command-map
   ("b" . helm-bibtex)
   ("B" . helm-bibtex-with-local-bibliography)
   ("n" . helm-bibtex-with-notes)
   ("<menu>" . helm-resume)
   )
  )
```

See the attached screenshot for the completion results, which include
`bibtex-completion-cite-commands`:

![image](https://github.com/tmalsburg/helm-bibtex/assets/11155854/f02b945d-9da4-4746-91ea-3f560e259a33)

**Comment by tmalsburg** [comment] 2023-05-16 07:02
Yes, it's sometimes really important in Emacs configurations to do things in the right order.  Glad you could fix it.

**Comment by hongyi-zhao** [comment] 2023-05-16 07:07
As you can see, I've removed all the advanced or fine-tuned configurations of this package, which in turn fixed the related problems. So, I'm still confused on the out-of-box using of the configurations represented in [README.org](https://github.com/tmalsburg/helm-bibtex#readme).

**Comment by tmalsburg** [comment] 2023-05-16 07:11
It shouldn't be necessary to remove all advanced configurations.  I think the last problem was simply that you tried to load helm-bibtex before helm was properly loaded.  Not sure though. In cases like this, it's useful start with a simple configuration that works and to then add features step by step.

**Comment by hongyi-zhao** [comment] 2023-05-16 07:27
Anyway, the minimum configuration above is sufficient for my usage scenario, therefore, I will not add functions step by step, at least now.
